# Generated by Django 4.1.3 on 2023-02-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usuario_managers_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='data_atendimento',
            field=models.DateTimeField(),
        ),
    ]
