# Generated by Django 4.1.3 on 2023-02-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_diaria_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='motivo_cancelamento',
            field=models.TextField(blank=True),
        ),
    ]
