# Generated by Django 4.1.3 on 2023-03-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_alter_servico_porcentagem_comissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='valor_quintal',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
